Repository Juratbek/upper_frontend, pull requests merged in 2022-11, with the labels that each got.

#249 242:fix/centering sidebar blog name and bio
  components/SidebarBlog/SidebarBlog.tsx
Labels: Fix

#251 238:feature/update blog avatar image
  components/Avatar/Avatar.module.scss
  components/Sidebar/Sidebar.tsx
  components/SidebarArticle/SidebarArticle.tsx
  frontends/profile/SettingsTab/components/AboutTab/AboutTab.tsx
  next.config.js
  pages/profile/index.tsx
  store/apis/config/api.constants.ts
  utils/blog.ts
  utils/image/compres.ts
  utils/image/index.ts
  utils/index.ts
Labels: feature

#253 252:enhancement/compressing image in editor image tool
  .env.development
  assets/icons.js
  components/Editor/services/editor-tools.ts
  components/FileInput/FileInput.types.ts
  components/Navigation/components/NavItem/NavItem.module.scss
  frontends/profile/SettingsTab/components/AboutTab/AboutTab.tsx
  public/logo.svg
Labels: enhancement

#255 254 adding amazon uri into image urls
  components/ApiErrorBoundary/ApiErrorBoundary.tsx
  components/Article/Article.tsx
  components/Navigation/Navigation.tsx
  components/Navigation/components/NavItem/NavItem.tsx
  components/Sidebar/Sidebar.tsx
  components/SidebarArticle/SidebarArticle.tsx
  frontends/article/components/ReadArticleSidebar/ReadArticleSidebar.tsx
  frontends/blog/FollowersTab/FollowersTab.tsx
  frontends/profile/FollowersTab/FollowersTab.tsx
  frontends/search/BlogsTab/BlogsTab.tsx
  pages/articles/[id]/index.tsx
  pages/blogs/[id]/index.tsx
  types/article.ts
  utils/article.ts
Labels: Fix

#257 256:enhancement/showing selected image
  frontends/profile/SettingsTab/components/AboutTab/AboutTab.tsx
Labels: enhancement

#261 259:fix/showing modal on blog unfollow
  assets/icons.js
  components/Avatar/Avatar.tsx
  components/Button/Button.module.scss
  components/Button/Button.tsx
  components/Modal/Modal.tsx
  components/Modal/Modal.types.ts
  pages/blogs/[id]/index.tsx
  public/logo.svg
Labels: bug, enhancement

#263 262:enhancement/validating register modal
  assets/icons.js
  components/Input/Input.module.scss
  components/Input/Input.tsx
  components/RegisterModal/RegisterModal.constants.ts
  components/RegisterModal/RegisterModal.module.scss
  components/RegisterModal/RegisterModal.tsx
  components/RegisterModal/RegisterModal.types.ts
  styles/globals.scss
  variables/icons.ts
Labels: enhancement

#265 264 show label description in write article and edit article pages
  components/MultiSelect/MultiSelect.module.scss
  components/MultiSelect/MultiSelect.tsx
  components/MultiSelect/MultiSelect.types.ts
  frontends/user-articles/UserArticlesSidebar.tsx
  frontends/write-article/sidebar-content.tsx
  styles/globals.scss
  utils/common.ts
Labels: enhancement

#277 264 show label description in write article and edit article pages
  components/Article/Article.tsx
  components/Blog/Blog.tsx
  components/Navigation/Navigation.module.scss
  components/Navigation/Navigation.tsx
  components/Sidebar/Sidebar.module.scss
  components/TabsHeader/TabsHeader.module.css
  components/TabsHeader/TabsHeader.module.scss
  components/TabsHeader/TabsHeader.tsx
  frontends/articles/ArticlesTab/ArticlesTab.tsx
  frontends/home/ForYouTab/ForYouTab.tsx
  frontends/home/TopTab/TopTab.tsx
  frontends/search/ArticlesTab/ArticlesTab.tsx
  frontends/search/BlogsTab/BlogsTab.tsx
  frontends/user-articles/UserArticlesSidebar.tsx
  frontends/write-article/write-article-page.tsx
  pages/_app.tsx
  pages/articles/[id]/index.tsx
  pages/search/index.tsx
  pages/user/articles/[id]/index.tsx
  styles/Search.module.css
  styles/Search.module.scss
  styles/_config.scss
  styles/_mixins.scss
  styles/_variables.scss
  styles/globals.scss
  styles/index.scss
  types/editor.ts
  types/index.ts
  utils/article.ts
  utils/device/device.constants.ts
  utils/device/device.ts
  utils/device/device.types.ts
  utils/index.ts
  variables/editor.ts
  variables/index.ts
Labels: feature

#275 269: Remove captions from image and embeds
  components/Editor/editor.tsx
  components/Editor/editor.types.ts
  frontends/user-articles/UserArticlesSidebar.tsx
  styles/_editorjs.scss
Labels: bug

#279 278:fix/adding loading state
  frontends/user-articles/UserArticlesSidebar.tsx
Labels: bug

#282 281:fix/set 5 seconds of caching for read article page
  pages/articles/[id]/index.tsx
Labels: Fix

#273 270: Avoid rendering editor for every save
  frontends/user-articles/UserArticlesSidebar.tsx
  pages/user/articles/[id]/index.tsx
Labels: Fix

#284 283:adding change login form into settings tab
  components/Alert/Alert.types.ts
  components/Alert/index.ts
  components/index.ts
  frontends/profile/SettingsTab/components/SecurityTab/SecurityTab.tsx
  frontends/profile/SettingsTab/components/SecurityTab/components/LoginForm.tsx
  frontends/profile/SettingsTab/components/SecurityTab/components/index.ts
  store/apis/blog/blog.api.ts
  store/apis/blog/blog.types.ts
Labels: feature

#287 268:feature/implement pagination in user articles page tabs
  components/Pagination/Pagination.module.scss
  components/Pagination/Pagination.tsx
  components/Pagination/Pagination.types.ts
  components/index.ts
  frontends/articles/ArticlesTab/ArticlesTab.tsx
  hooks/useUrlParams/useUrlParams.ts
  hooks/useUrlParams/useUrlParams.types.ts
  store/apis/article/article.api.ts
  styles/globals.scss
  types/index.ts
  types/request.ts
  types/response.ts
  variables/common.ts
Labels: feature

#286 276: Inserted <a> tags inside Links
  components/Article/Article.tsx
  components/Author/Author.tsx
  components/Blog/Blog.tsx
  components/Follower/Follower.tsx
  components/SidebarArticle/SidebarArticle.tsx
  components/SidebarBlog/SidebarBlog.tsx
  components/SidebarSearch/SidebarSearch.tsx
  frontends/articles/ArticlesTab/ArticlesTab.tsx
Labels: Fix

#289 288:fix/some date workings
  components/Article/Article.tsx
  frontends/article/article-page.tsx
  frontends/blog/AboutTab/AboutTab.tsx
  utils/date/date.ts
Labels: Fix

#291 274:enhancement/creating Head component
  components/Head/Head.tsx
  components/Head/Head.types.ts
  components/Head/index.ts
  components/index.ts
  pages/articles/[id]/index.tsx
  pages/blogs/[id]/index.tsx
  utils/article.ts
  utils/blog.ts
Labels: enhancement

#294 290 add badge for notifications
  components/Badge/Badge.module.scss
  components/Badge/Badge.tsx
  components/Badge/Badge.types.ts
  components/Navigation/Navigation.tsx
  components/Navigation/components/NavItem/NavItem.module.scss
  components/Navigation/components/NavItem/NavItem.tsx
  components/Navigation/components/NavItem/NavItem.types.ts
  components/index.ts
  store/apis/notification/notification.api.ts
  variables/notification.ts
Labels: feature

#295 290:enhancement/adding border radius for article img
  components/ArticleImg/ArticleImg.module.css
  components/ArticleImg/ArticleImg.module.scss
  components/ArticleImg/ArticleImg.tsx
Labels: enhancement

#298 296:add pagination in notificaitons page
  components/Pagination/Pagination.tsx
  frontends/notifications/NotificationsTab/NotificationsTab.tsx
  store/apis/notification/notification.api.ts
Labels: feature

#299 297:fix/removing useEffect from useAuth, adding the useEffect into _a…
  hooks/useAuth/useAuth.tsx
  hooks/useAuth/useAuth.types.ts
  pages/_app.tsx
Labels: Fix

#300 272:enhancement/adding tooltip for navigation icons
  components/Navigation/Navigation.constants.ts
  components/Navigation/Navigation.tsx
  components/Navigation/Navigation.types.ts
  components/Tooltip/Tooltip.module.scss
  components/Tooltip/Tooltip.tsx
  components/Tooltip/Tooltip.types.ts
  components/index.ts
Labels: enhancement

#301 232:fix/uncommenting window reload
  hooks/useNextAuth/useNextAuth.ts
  store/middlewares/apiErrorMiddleware.ts
  utils/auth/index.ts
  utils/auth/next-auth.ts
Labels: Fix

#306 303:enhancement/adding head component in _app.tsx
  components/Head/Head.tsx
  pages/_app.tsx
Labels: feature

#307 304:enhancement/make article item content 3 lined with css
  components/Article/Article.module.scss
Labels: enhancement

#310 304:enhancement/showing api error on creating article
  frontends/write-article/sidebar-content.tsx
Labels: enhancement

#309 271 decrise unsplash url image size
  components/Editor/services/editor-tools.ts
  frontends/user-articles/UserArticlesSidebar.tsx
  frontends/write-article/sidebar-content.tsx
  store/apis/config/api.constants.ts
  utils/article.ts
  utils/image/compress.ts
  utils/image/index.ts
Labels: Fix

#313 312:fix/making UI responsive for large screends
  components/Navigation/Navigation.module.scss
  styles/_editorjs.scss
  styles/_mixins.scss
  styles/globals.scss
Labels: Fix

#317 316:enhancement/reconstructing article actions
  components/ArticleStatus/ArticleStatus.constants.ts
  components/Button/Button.module.scss
  components/Button/Button.tsx
  frontends/user-articles/UserArticlesSidebar.constants.ts
  frontends/user-articles/UserArticlesSidebar.tsx
  frontends/user-articles/UserArticlesSidebar.types.ts
  hooks/index.ts
  hooks/useModal/useModal.ts
  pages/user/articles/[id]/index.tsx
  store/apis/article/article.api.ts
  store/apis/article/article.endpoints.ts
  styles/globals.scss
  types/article.ts
  variables/Articles.constants.ts
  variables/article.ts
Labels: enhancement

#320 318:checking unsplash url on compressing
  frontends/user-articles/UserArticlesSidebar.tsx
  store/apis/label/label.api.ts
  utils/image/compress.ts
Labels: Fix

#322 319:enhancement/changing article not fount message
  pages/articles/[id]/index.tsx
Labels: enhancement

#323 319:fix/checking api endpoint
  store/middlewares/apiErrorMiddleware.ts
Labels: Fix

#325 267:enhancement/animating comments sidebar
  components/Sidebar/Sidebar.module.scss
  components/Sidebar/Sidebar.tsx
  utils/device/device.ts
Labels: enhancement

#327 267:fix/checking for getTokenApi
  store/middlewares/apiErrorMiddleware.ts
Labels: Fix

#349 343:fix/show alert with error message from backend
  components/Alert/Alert.module.scss
  frontends/user-articles/UserArticlesSidebar.tsx
Labels: Fix

#350 335:fix/translate sidebar search labe
  components/SidebarSearch/SidebarSearch.tsx
Labels: Fix

#351 334:fix/closing modal
  components/LoginModal/LoginModal.tsx
Labels: Fix

#353 344:dispatching published article
  frontends/user-articles/UserArticlesSidebar.tsx
  store/apis/article/article.api.ts
Labels: Fix

#354 346:showing no results UI
  components/SidebarSearch/SidebarSearch.tsx
Labels: Fix

#355 345 add scroll for sidebar
  components/Sidebar/Sidebar.module.scss
  components/Sidebar/Sidebar.tsx
Labels: Fix

#357 338:enhancement/adding x to multi select item
  components/MultiSelect/MultiSelect.module.scss
  components/MultiSelect/MultiSelect.tsx
Labels: enhancement

#358 336:fix/show 'Siz uchun' tab only for authenticated users
  frontends/home/Home.constants.ts
  pages/index.tsx
  types/common.ts
Labels: Fix

#360 359: save changes before publishing
  frontends/user-articles/UserArticlesSidebar.tsx
Labels: enhancement

#361 341:enhancement/change publish modal UI
  frontends/user-articles/UserArticlesSidebar.tsx
Labels: enhancement

#363 342:fix/fixing compress image util
  frontends/user-articles/UserArticlesSidebar.tsx
  frontends/write-article/write-article-page.tsx
  pages/user/articles/[id]/index.tsx
  styles/globals.scss
  utils/article.ts
  utils/image/compress.ts
Labels: Fix

#365 332:fix/using spinner as a loader
  components/Editor/editor.tsx
  components/EditorSpinner/EditorSpinner.module.scss
  components/EditorSpinner/EditorSpinner.tsx
  components/index.ts
  pages/user/articles/[id]/index.tsx
Labels: enhancement

#367 267 making UI responsive for mobile tablet and large screens
  assets/icons.js
  components/Navigation/Navigation.module.scss
  components/Navigation/Navigation.tsx
  components/Sidebar/Sidebar.module.scss
  components/Sidebar/Sidebar.tsx
  store/states/index.ts
  store/states/sidebar/index.ts
  store/states/sidebar/sidebarSelector.ts
  store/states/sidebar/sidebarSlice.ts
  store/store.ts
  styles/_variables.scss
  styles/globals.scss
  variables/icons.ts
Labels: Fix

#368 267:fix/fixing sidebar UI issue
  components/Sidebar/Sidebar.module.scss
  frontends/article/components/ArticleActions/article-actions.tsx
Labels: Fix

#369 308 add footer into main section
  .husky/pre-commit
  components/Footer/Footer.module.scss
  components/Footer/Footer.tsx
  components/Footer/index.ts
  components/index.ts
  frontends/profile/StatisticsTab/StatisticsTab.tsx
  pages/_app.tsx
  pages/about/index.tsx
  pages/contact/index.tsx
  pages/team/index.tsx
  styles/globals.scss
  variables/common.ts
Labels: feature

#371 366:enhancement/opening logout modal on logout icon click
  components/LogoutModal/LogoutModal.tsx
  components/Modal/Modal.module.scss
  components/Navigation/Navigation.tsx
  components/index.ts
  store/states/index.ts
  store/states/logoutModal/index.ts
  store/states/logoutModal/logoutModalSelector.ts
  store/states/logoutModal/logoutModalSlice.ts
  store/store.ts
Labels: enhancement

#373 372:fetching doc by id
  components/Footer/Footer.module.scss
  components/Footer/Footer.tsx
  frontends/docs/sidebar/DocsSidebar.constants.ts
  frontends/docs/sidebar/DocsSidebar.tsx
  pages/docs/[id]/index.tsx
  pages/docs/blogging/index.tsx
  pages/docs/write-article/features/alert/index.tsx
  pages/docs/write-article/features/code/index.tsx
  pages/docs/write-article/features/delimeter/index.tsx
  pages/docs/write-article/features/header/index.tsx
  pages/docs/write-article/features/image/index.tsx
  pages/docs/write-article/features/list/index.tsx
  pages/docs/write-article/features/text/index.tsx
  pages/docs/write-article/introduction/quick-start/index.tsx
  pages/docs/write-article/settings/delete/index.tsx
  pages/docs/write-article/settings/publish/index.tsx
  pages/docs/write-article/settings/save/index.tsx
  pages/docs/write-article/settings/statuses/index.tsx
  pages/docs/write-article/settings/tegs/index.tsx
  pages/docs/write-article/settings/unpublish/index.tsx
  store/apis/docs/docs.api.ts
  store/apis/docs/index.ts
  store/apis/index.ts
  store/store.ts
Labels: feature

#380 376:fix/making article skeleton and footer responsive for mobile UI
  components/Footer/Footer.module.scss
  components/skeletons/ArticleSkeleton/ArticleSkeleton.tsx
Labels: Fix

#384 382:enhancement/handling create article response
  frontends/write-article/sidebar-content.tsx
Labels: enhancement

#386 385:enhancement/change default avatar image
  components/Avatar/Avatar.tsx
  public/social_medi_logo.png
Labels: enhancement

#389 387:enhancement/adding skeleton
  frontends/blog/FollowersTab/FollowersTab.tsx
  frontends/profile/FollowersTab/FollowersTab.tsx
  styles/globals.scss
Labels: enhancement

#390 388:fix/dropping subscribe button on mobile UI
  frontends/blog/Blog.tsx
Labels: Fix
